### ISSUE TITLE
Design Issue

### ISSUE THREAD

**Issue by kevinbluett** [DUCSS/ducss-site-old#4]
If the text of one of the events is too long, is pushes down the next event as can be seen in the screenshot attached.
![screen shot 2013-11-10 at 15 48 15](https://f.cloud.github.com/assets/687114/1508856/891051a8-4a1f-11e3-91bf-008e2cd48d9b.png)

**Comment by IanConnolly** [comment]
Confirmed on Firefox 25 on OSX 10.9
