### ISSUE TITLE
Order of events on the "All Events" page is illogical

### ISSUE THREAD

**Issue by kevinbluett** [DUCSS/ducss-site-old#5]
Order of events on the "All Events" page is illogical as can be seen on this page
![screen shot 2013-11-10 at 15 48 15](https://f.cloud.github.com/assets/687114/1508857/b15d1042-4a1f-11e3-8d31-73a3aab94a56.png)

**Comment by kevinbluett** [comment]
Order issue caused by the design issue ( #4 ), as the element is begin pushed down and hence a duplicate.

**Comment by houli** [comment]
Will need to write docs for how to set up an instance, DNS, installing Dokku and database, creating an app.
